export const ADD_LINK = 'ADD_LINK';
export const DELETE_LINK = 'DELETE_LINK';

export const ADD_GROUP = 'ADD_GROUP';
export const CHANGE_GROUP_COLOR = 'CHANGE_GROUP_COLOR';
export const MOVE_LINK_TO_GROUP = 'MOVE_LINK_TO_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';

export const CHANGE_DASHBOARD_BACKGROUND_COLOR = 'CHANGE_DASHBOARD_BACKGROUND_COLOR';
export const TOGGLE_DASHBOARD_BOTTOM_PANEL_VISIBILITY = 'TOGGLE_DASHBOARD_BOTTOM_PANEL_VISIBILITY';
export const CHANGE_BOTTOM_PANEL_CONTENT = 'CHANGE_BOTTOM_PANEL_CONTENT';