export const CHANGE_DASHBOARD_BACKGROUND_COLOR = 'CHANGE_DASHBOARD_BACKGROUND_COLOR';
export const TOGGLE_DASHBOARD_BOTTOM_PANEL_VISIBILITY = 'TOGGLE_DASHBOARD_BOTTOM_PANEL_VISIBILITY';

export const APOLLO_QUERY_RESULT = 'APOLLO_QUERY_RESULT';
export const APOLLO_QUERY_INIT = 'APOLLO_QUERY_INIT';